import jsPDF from "jspdf";

const downloadResumeReport = ({ user, report }) => {
  if (!report) {
    alert("No report available.");
    return;
  }

  const doc = new jsPDF();

  const PAGE_HEIGHT = 280;
  let y = 20;

  const checkPage = () => {
    if (y > PAGE_HEIGHT) {
      doc.addPage();
      y = 20;
    }
  };

  const addSectionTitle = (title) => {
    checkPage();
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text(title, 20, y);
    y += 10;
  };

  const addBulletList = (items) => {
    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");

    if (!items || items.length === 0) {
      doc.text("None", 25, y);
      y += 8;
      return;
    }

    items.forEach((item) => {
      checkPage();

      const lines = doc.splitTextToSize(`• ${item}`, 170);

      doc.text(lines, 25, y);

      y += lines.length * 7;
    });

    y += 6;
  };

  // ===============================
  // Header
  // ===============================

  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.text("AI Resume Analysis Report", 20, y);

  y += 15;

  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");

  doc.text(`Name : ${user?.name || "User"}`, 20, y);
  y += 8;

  doc.text(`Email : ${user?.email || "N/A"}`, 20, y);
  y += 8;

  doc.text(`Generated : ${new Date().toLocaleString()}`, 20, y);

  y += 15;

  // ===============================
  // ATS Score
  // ===============================

  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);

  doc.text(`ATS Score : ${report.atsScore ?? 0}%`, 20, y);

  y += 15;

  // ===============================
  // Summary
  // ===============================

  addSectionTitle("Resume Summary");

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);

  const summary = doc.splitTextToSize(
    report.summary || "No summary available.",
    170
  );

  doc.text(summary, 20, y);

  y += summary.length * 7 + 10;

  // ===============================
  // Strengths
  // ===============================

  addSectionTitle("Strengths");
  addBulletList(report.strengths);

  // ===============================
  // Weaknesses
  // ===============================

  addSectionTitle("Weaknesses");
  addBulletList(report.weaknesses);

  // ===============================
  // Missing Skills
  // ===============================

  addSectionTitle("Missing Skills");
  addBulletList(report.missingSkills);

  // ===============================
  // AI Recommendations
  // ===============================

  addSectionTitle("AI Recommendations");
  addBulletList(report.recommendations);

  // ===============================
  // Footer
  // ===============================

  checkPage();

  y += 10;

  doc.setFontSize(10);

  doc.text(
    "Generated by AI Interview Preparation System",
    20,
    y
  );

  doc.save(`Resume_Report_${user?.name || "User"}.pdf`);
};

export default downloadResumeReport;